spring:
  cloud:
    gateway:
      routes:
        - id: ticket_route
          uri: http://localhost:8081
          predicates:
            - Path=/tickets/**
        - id: schedule_route
          uri: http://localhost:8082
          predicates:
            - Path=/schedules/**
  main:
    web-application-type: reactive
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


